theme: jekyll-theme-minimal
title: Dear Auditor,
description: a love letter to auditors from devops, where we promise to make life better
logo: /images/dear-auditor-logo.png
show_downloads: true
google_analytics: UA-117437068-1
